### ISSUE TITLE
Generate solidity code to encode calldata struct

### ISSUE THREAD

**Issue by taobun** [bandprotocol/bandchain#1289]
Let's scan can generate solidity code to encode calldata struct to bytes from the schema.

**Comment by evilpeach** [comment]
@taobun I think it's already been done.

**Comment by evilpeach** [comment]
@tansawit done?

**Comment by tansawit** [comment]
@evilpeach i don’t think so. As far as I know/checked we only have the encode function generation for Go (I.e. encodeStructGo in Borsh.re)

**Comment by evilpeach** [comment]
Done and moved to [Here](https://github.com/bandprotocol/cosmoscan)
