### ISSUE TITLE
Stress test Wenchang operations

### ISSUE THREAD

**Issue by sorawit** [bandprotocol/bandchain#1356]
Using BigDipper as the base explorer, test interacting with Wenchang testnet and report.
- [x] Send money
- [x] Spam sending money from 100 accounts to the network concurrently
- [x] Delegate
- [x] Withdraw delegation
- [x] Double sign and get jailed
- [x] Apply for validator then keep it down forever (and verify that it will get slashed and jail in 1 day)f
- [x] All proposal related messages

**Comment by taobun** [comment]
All tests have been done
