### ISSUE TITLE
Make GraphQL & Hasura ready for produciton

### ISSUE THREAD

**Issue by evilpeach** [bandprotocol/bandchain#1432]
- No more using docker.
- Investigate and use services on AWS for this.
- Contact @taobun or @sorawit for more details.

Ref: [Hasura Checklist](https://hasura.io/docs/1.0/graphql/manual/deployment/production-checklist.html)

**Comment by sorawit** [comment]
We have a testnet version now up on https://graphql-wt2-lb.bandchain.org/console with read-only permission.
