### ISSUE TITLE
Fix TxSub to snake_case version of msg

### ISSUE THREAD

**Issue by taobun** [bandprotocol/bandchain#1538]
Chain has been updated to use Protobuf to declare message type. That makes json representation change from camelCase to snake_case, so we need to update scan to this change. Please send all tx to make sure no missing msg that will make our scan crashed.

**Comment by sorawit** [comment]
@evilpeach Ticket already exists. Please fill in points accordingly.

**Comment by sorawit** [comment]
Duplicated with #1544
