### ISSUE TITLE
Multi validators docker setup for new band oracled

### ISSUE THREAD

**Issue by taobun** [bandprotocol/bandchain#1702]
We need script for starting 4 nodes with new oracled that register all reporter keys to chain and ready to report data to chain combine with query node + DB + Hasura using in develop chain.

Details:
- [x] Write deployment script
- [x] Deploy on d3n.bandprotocol.com
- [ ] Write instruction on Wiki

**Comment by sorawit** [comment]
@taobun can we close this?

**Comment by taobun** [comment]
Yep currently just run command `./docker-config/start.sh`
