### ISSUE TITLE
bandd v1.0.5 does not run on centos 7

### ISSUE THREAD

**Issue by westaking** [bandprotocol/bandchain#2239]
bandd v1.0.5 does not run on centos 7 for the following reasons:

```
$bandd

bandd: /usr/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/jun/go/src/github.com/bandprotocol/bandchain/go-owasm/api/libgo_owasm.so)
```

**Comment by westaking** [comment]
I had the same problem with go-cosmwasm, but that solved it.
https://github.com/CosmWasm/go-cosmwasm/issues/32

**Comment by sorawit** [comment]
@westaking Thanks for the pointer. We will take a look and fix it.

**Comment by westaking** [comment]
solved.
https://github.com/bandprotocol/bandchain/issues/2271
