### ISSUE TITLE
Minor issue with Token Economic's Wiki

### ISSUE THREAD

**Issue by michelboaventura** [bandprotocol/bandchain#2335]
There is a missing parenthesis on https://github.com/bandprotocol/bandchain/wiki/Token-Economics#validators-and-stakers at ``[fee](#gas-and-network-fee``. It seems there is no way to send PRs to update wiki content, so I'm creating this issue.

Thanks.

**Comment by tansawit** [comment]
Hey there @michelboaventura!

Apologies for getting back to you so late. Thank you for the catch! As for the PRs, as you might have seen from the wiki pages, we are moving to a dedicated site. The repo for that is now available [here](https://github.com/bandprotocol/bandchain-docs) in case you're interested. The documentation itself is also now hosted at [docs.bandchain.org](https://docs.bandchain.org)

**Comment by michelboaventura** [comment]
Thank you @tansawit, I will take a look at the new documentation repo.

Cheers
