### ISSUE TITLE
"Running with Docker" section outdated

### ISSUE THREAD

**Issue by jun0tpyrc** [bandprotocol/bandchain#2468]
Hello there, I would like to report that instructions in this section are outdated.
(https://github.com/bandprotocol/bandchain#run-on-4-validators)

Paths are outdated in doc , it looks to be  `chain/scripts/generate_genesis.sh` instead ,
and upon running it showed `ERROR: unknown flag: --keyring-backend` errors without stopping.

I was using binaries for `v0.2.4 - Wenchang` release. Is the docker script only for alpha versions binaries?
Thanks.

**Comment by jun0tpyrc** [comment]
I found https://github.com/bandprotocol/bandchain/blob/master/chain/build.md
For building upon latest master, what version do I actually get and is it a binary that can safely interact with the current public testnet & mainnet?

**Comment by sorawit** [comment]
Hi @juno-yu-crypto. Master branch is not compatible with the current BandChain mainnet. Please follow instruction here for how to run the mainnet: https://medium.com/bandprotocol/bandchain-wenchang-stage-3-begins-with-public-node-12e31ff2c0e
