### ISSUE TITLE
What is the faucet address of your wenchang testnet?

### ISSUE THREAD

**Issue by liuxh-go** [bandprotocol/bandchain#2488]
What is the faucet address of your wenchang testnet? I clicked get 10 testnet BAND on the block explorer to no avail! I sent an email to connect@bandprotocol.com and did not receive any test coins! ! !

**Comment by taobun** [comment]
Wenchang testnet has not been maintained anymore. If you want to test our network please test on https://guanyu-testnet2.cosmoscan.io or use on mainnet.
