### ISSUE TITLE
Cannot use syn 1.0.60 in obi-derive-internal

### ISSUE THREAD

**Issue by qapquiz** [bandprotocol/bandchain#3112]
when import obi = "0.0.1" from crates.io there are an error that cannot find syn::export
![image](https://user-images.githubusercontent.com/1768460/105815309-4bdf3180-5fe5-11eb-9db4-d1272f26e525.png)

I found an solution from syn project.
• change from syn::export::TokenStream2 to proc_macro2::TokenSteram as TokenStream2
• syn::export::{ToTokens} to quote::ToTokens;
• syn::export::Span to proc_macro2::Span;

Is it okay to pull request with these fixes?

**Comment by taobun** [comment]
Sorry for late reply, we will pin our syn version to 1.0.57 and publish new version for that change

**Comment by taobun** [comment]
@qapquiz this issue is now solved in version 0.0.2 https://crates.io/crates/obi
