### ISSUE TITLE
Fix incomplete code for contract1 - Simple decentralized exchange

### ISSUE THREAD

**Issue by prin-r** [bandprotocol/bandchain#374]
See https://github.com/bandprotocol/d3n/pull/366
- Can't it just import Bridge.sol?
- Take this as parameter?
- Let's make this extend ERC 20 and work only for one parameter
- This format is not acceptable

**Comment by sorawit** [comment]
@prin-r @taobun is #379 working on this?

**Comment by sorawit** [comment]
I think this is fixed already.
