### ISSUE TITLE
Quick resolve when every validator report data

### ISSUE THREAD

**Issue by taobun** [bandprotocol/bandchain#387]
After every end block not only check that pending request need to resolve at this block or not, but call execution immediately when all validator report data for that request

Implementation plan
- [ ] Check resolve condition in `handler.go`
- [ ] Add unit test make sure quick resolve work correctly
- [ ] Test end-to-end in local chain make sure chain get result immediately last report has been submitted.

**Comment by sorawit** [comment]
I know this is tricky, especially when one validator goes down. But let's just make this work when *ALL* validators (all 4 of them on alphanet) report the data. That means if one goes down this will be completely useless (for now).
