### ISSUE TITLE
Design new validator report job

### ISSUE THREAD

**Issue by taobun** [bandprotocol/bandchain#389]
Currently we use subscription model to track new request for each provider and run together with chain. It look like just one program that seem make sense in the early development, but it 's pain for us now

Specification of new program
- Independence from core chain for we can control and reset if we have problems without touch core chain.
- Abandon subscription model and using poll request and report
- Make sure can handle request come in the meantime and send every report transactions completely

We can discuss new design with @sorawit and @taobun and make ticket for implementation later.

**Comment by sorawit** [comment]
@taobun Let's mark this done after you have tickets for the poll program

**Comment by taobun** [comment]
There are 3 tickets for this program #390 #426 #427
