### ISSUE TITLE
Define specification of public api

### ISSUE THREAD

**Issue by taobun** [bandprotocol/bandchain#407]
This is the API for external developer to interact with D3N programmatically, instead of needing to go to the explorer page and request data + copy proof. 

The endpoint is already there. Just need to spec it up. 

- Estimate what we have and what we need to do more and make ticket of addition works

**Comment by evilpeach** [comment]
I'm working on [this api spec](https://documenter.getpostman.com/view/10283798/SWTEcbUC?version=latest#f6cb9d52-e01e-4a50-80d7-094c60d05caf) and [this mock server](https://2e4b8eeb-3974-40a5-ac76-10f183c61d12.mock.pstmn.io/request/1) is for testing in development.

**Comment by evilpeach** [comment]
This is fixed by #430 #431 #432 #433
