### ISSUE TITLE
Add swagger-ui to the project 

### ISSUE THREAD

**Issue by sorawit** [bandprotocol/bandchain#533]
Figure out how we can build and maintain the spec of our 1317 endpoint with swagger. Cosmos already have the config file for them already. Also figure out the step to deploy and access the page.

Some reference:
- https://cosmos.network/rpc/#/
- https://github.com/cosmos/cosmos-sdk/blob/master/client/lcd/swagger-ui/swagger.yaml

**Comment by evilpeach** [comment]
Ref: https://github.com/swagger-api/swagger-editor
https://swagger.io/docs/open-source-tools/swagger-editor/
