### ISSUE TITLE
[Bug] Tx subscriber `Server error: subscription was cancelled (reason: client is not pulling messages fast enough)

### ISSUE THREAD

**Issue by taobun** [bandprotocol/bandchain#61]
Event subscriber from tendermint stop subscribe after listen 4 reports in one block

How to produce?
Run chain with 4 validators when request has been executed. All 4 validators send report to chain in the same block, but tendermint server cannot handle report event correctly. (Internal buffer is full with capacity = 1)

Possible root cause
After experiment error come from `https://github.com/tendermint/tendermint/blob/master/libs/pubsub/pubsub.go` in `send` function. Code cannot push new event to channel because it's full. Consumer is `https://github.com/tendermint/tendermint/blob/master/rpc/core/events.go` that consume data after new event push make pubsub return error and try to cancel subscription.

- But ws client have code to resub after got error but code doesn't work out as expect. It return error told that already subscribe

Way to solve
- Make sure consumer consume event fast enough (?) for new event
- Increase buffer size of buffer
- Make resubscription work as code expected

**Comment by sorawit** [comment]
This needs to be fixed prior to the demo. IMO the easiest fix would be to use polling in subscriber code.
