### ISSUE TITLE
Explore what happen when cosmos context out of gas between wasm runtime

### ISSUE THREAD

**Issue by taobun** [bandprotocol/bandchain#639]
- Create a mock environment that makes out of gas between run VM (prepare or execute)
- Make sure after out of gas, every action must stop and return out of gas in chain scope like normal end of gas behavior.

Knowledge about this issue:
- How to recover panic of Perlin [code](https://github.com/perlin-network/life/blob/master/exec/helpers.go)
- How cosmos manage gas [code](https://github.com/cosmos/cosmos-sdk/blob/release/v0.37.7/store/types/gas.go)

**Comment by sorawit** [comment]
Close in favor of #947. We will re-architect code so there's no extra gas usage during wasm call.
