### ISSUE TITLE
Design block explorer account index page

### ISSUE THREAD

**Issue by sorawit** [bandprotocol/bandchain#657]
Should reuse what paul already did as the guideline

**Comment by prin-r** [comment]
For "Account Index" page @smiled0g think that we can somehow improve visual hierarchy for showing balances. Anyway the current design is good enough for now.

**Comment by prin-r** [comment]
TODO Next
- Improve the balances![Screen Shot 2563-03-04 at 11.15.31.png](https://images.zenhubusercontent.com/5daea517b2c98a0001a6d87f/669afc65-4e85-46ac-8e29-13cd6383f110)
