### ISSUE TITLE
Make sure we can have all data for block explorer

### ISSUE THREAD

**Issue by sorawit** [bandprotocol/bandchain#675]
Go over all pages in scan wireframe and make sure the node can serve data for the web. Note for data that is not currently available to derive plan further.

As the result of this ticket, we should have a sheet to track all information that we need

**Comment by evilpeach** [comment]
@sorawit @taobun I've listed all used variables on every page.  https://docs.google.com/spreadsheets/d/1JwzzcJl0bDQdi1I8T3KiZloRX6RaGvZ3Vi4ZIRmUbCM/edit#gid=0
