### ISSUE TITLE
Make bandoracled read keys from bandd directory

### ISSUE THREAD

**Issue by sorawit** [bandprotocol/bandchain#680]

**Comment by evilpeach** [comment]
As I found, the `bandoracled` must use the private key from an account in the `bandcli`. It didn't read from `priv_validator_key.json`.  We have to find a new way to get the private key for `bandoracled`.

**Comment by evilpeach** [comment]
@sorawit @taobun Should we close this ticket? Then, creating an issue of the new approach.

**Comment by sorawit** [comment]
Swit is already working on this. Custom folder for keys of bandoracled.
