### ISSUE TITLE
Update scan URL route scheme

### ISSUE THREAD

**Issue by sorawit** [bandprotocol/bandchain#821]
- `/validators`
- `/sources`
- `/scripts`
- `/blocks`
- `/txs`
- `/DXXXX`, `/OXXXX`, `/BXXXX`, `/RXXXX`
- `/bandxxxxxxx`
- `/bandvaloperxxxxx`
- `/tx/DEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEFDEADBEEF`

**Comment by evilpeach** [comment]
Moved to [Here](https://github.com/bandprotocol/cosmoscan)
