### ISSUE TITLE
Explore Kadena blockchain

### ISSUE THREAD

**Issue by sorawit** [bandprotocol/bandchain#840]
Spend a day playing around Kadena tools and ecosystem. Write smart contracts there and present the findings with the team. https://www.kadena.io/developers

Overview topic:
- [x] What 're components for this ecosystem (Kadena, Pact, Kuro, wallet etc)
- [x] Can summarize each component
- [x] Follow the tutorial and summarize how to implement smart contract by PACT
- [x] Present how transaction is represented.
- [x] How contracts interaction work 
- [ ] Deploy mock bridge and example contract in testnet

**Comment by prin-r** [comment]
- Kadena Chain (Overview)
    - Parallel multi-chain Proof-of-Work architecture
        - Allow for high transaction throughput
    - Pact smart contract language and its formal verification system
    - Built-in governance mechanisms for smart contracts
    - Native support for oracles, REST APIs and database integrations
    - Ecosystem
        - Explorer
        - Wallet
            - Chainweaver - Cryptocurrency & Smart Contract Wallet
        - Faucet
            - Create Account
            - Fund Account
            - Check Balance
        - Online Editor
- Pack Lang
    - Inspire by Bitcoin script
    - LISP-like syntax
    - Functional
    - Has type inference
    - Turing-Incomplete
        - Cannot run unbounded loop or recursive
    - Human Readable
    - Formal Verification
        - Using Z3 from Microsoft
    - 3 core elements
        - Module
            - Logic of smart contract
            - Contains definition of functions, tables, schemas, const value
            - Not contains Keysets, Table creation, Function Calls
            - Module name needs to be unique across all module names that exist on the blockchain
        - Keysets
            - Contain keys which are an important part of acquiring the signatures needed to verify a transaction
        - Tables
            - Tables are defined using deftable
- Online Editor
    - Consist of 3 parts
        - Nav
        - Left (Coding)
        - Right
            - Env
                - Keysets tab
                    - Keysets List
                        - Keys-all
                        - Keys-2
                        - Keys-any
                    - Local Storage Wallet
                - Raw JSON keysets
                - Result of keysets
            - REPL (run eval print loop) or Pack terminal
                - ”reset” is one of the spacial command
            - Messages
                - Show log when interacting with chain
                - Same functionality as bottom panel in remix
            - Module Explorer
                - Can select chain id
                - Explore deployed modules
                - Test calling a module
                - Load code of a module
- Smart contract interaction
                - Implement example contract

**Comment by prin-r** [comment]
TODO Next
    - Figure out errors when deploy and send transaction
    - Verify if Pack's sha256 is the same as Solidity’s sha256
    - Figure out how to get Ecrecovery for Pack smart contract
