### ISSUE TITLE
Design and implement caching layer for request tables

### ISSUE THREAD

**Issue by sorawit** [bandprotocol/bandchain#928]
Must have all info necessary for request index page. It may use more than 1 table. Need to discuss design with @sorawit and @taobun

Request 
ID: int64 (pk),
OracleScriptID: int64 (fk, OracleScript),
Calldata: JsBuffer.t,
SufficientValidatorCount: int,
ExpirationHeight: int,
ResolveStatus: string,
Requester: Address.t,
TxHash: Hash.t (fk Transaction),
Result: []byte,

RequestedValidator
RequestID: int64 (pk,fk Request)
ValidatorAddress: string (pk,fk Validator)
    
RawDataRequests
RequestID: int64(pk,fk Request)
ExternalID: int64(pk)
DataSourceID: int64 (fk DataSource)
Calldata: []byte

**Comment by Benzbeeb** [comment]
request rawdatarequest
